config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    if @review.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def flat_params
    params.require(:flat).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<%# <div class="max-w-lg mx-auto mt-16 text-center max-w-sm rounded overflow-hidden shadow-lg p-10">
  <h1 class="mb-4 text-3xl font-black">Here are all our Flats!</h1>
  <p class="text-lg leading-snug">If this looks nice, it means Tailwind is set up properly.</p>
</div> %>

<h1 class="text-3xl p-10 mx-auto text-center">All Flats</h1>
<div class="flex flex-wrap">
<% @flats.each do |flat| %>
  <div class="xl:w-1/3 md:w-1/2 p-4">
    <div
      class="
        c-card
        block
        bg-white
        shadow-md
        hover:shadow-xl
        rounded-lg
        overflow-hidden
      "
    >
      <img
        class="
          lg:h-60
          xl:h-56
          md:h-64
          sm:h-72
          xs:h-72
          h-72
          rounded
          w-full
          object-cover object-center
          mb-4
        "
        src="https://picsum.photos/720/400"
        alt="Image Size 720x400"
      />
      <div class="p-4">
        <h2
          class="
            text-lg text-gray-900
            font-medium
            title-font
            whitespace-nowrap
            truncate
            ...
          "
        >
          <%= flat.name %>
        </h2>
        <p class="font-light mb-4 text-sm text-gray-600">
          <%= flat.address %>
        </p>
        <p
          class="
            text-gray-600
            font-light
            text-md
            whitespace-nowrap
            truncate
            ...
          "
        >
          <%= flat.description %>
          <br />
        </p>


        <p>
          <%= link_to "Read More", flat_path(flat), class:"inline-flex text-indigo-500" %>
        </p>
        <div class="pt-4 border-t text-xs text-gray-700">
          <div class="flex justify-between">
            <div>
              Guests:
              <span
                class="
                  inline-flex
                  items-center
                  justify-center
                  px-2
                  py-1
                  text-xs
                  font-bold
                  leading-none
                  text-white
                  bg-red-400
                  rounded-full
                "
                ><%= flat.number_of_guests %></span
              >
            </div>

            <div>
              Price:
              <span
                class="
                  inline-flex
                  items-center
                  justify-center
                  px-2
                  py-1
                  text-xs
                  font-bold
                  leading-none
                  text-white
                  bg-blue-400
                  rounded-full
                "
                >$ <%= flat.price_per_night %></span
              >
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
<% end %>
</div>

app/views/flats/show.html.erb
<div class="relative">
  <img
    class="
      rounded
      w-full
      object-cover object-center
      mb-4
      h-80
      "
      src="https://picsum.photos/720/400"
      alt="Image Size 720x400"
  />
  <div class="px-20 grid grid-cols-3 gap-4 absolute top-40">
    <div class="col-span-2">
      <div class="bg-gradient-to-r from-gray-100 to-gray-200 rounded py-3 px-4 mb-4">
        <p class="text-3xl mb-1"><%= @flat.name %></p>
        <p class="text-md"><%= @flat.address %></p>
      </div>
      <div class ="bg-gray-100 rounded py-3 px-4 mb-4">
        <p class ="text-xl mb-1">A bit more about this flat...</p>
        <p class ="text-sm"><%= @flat.description %></p>
      </div>
      <div class="bg-gray-100 rounded py-3 px-4 mb-4">
        <p class ="text-xl mb-1">Details</p>
        <div class="flex justify-between">
          <p>Max guests: <%= @flat.number_of_guests %></p>
          <p>Price: $ <%= @flat.price_per_night %></p>
        </div>
      </div>
    </div>
    <div class="col-span-1">
      <div class="bg-gray-100 rounded p-2">
        <%= simple_form_for [ @flat ] do |f| %>
          <%= f.input :name, class:"my-1" %>
          <%= f.input :address %>
          <%= f.submit "Book", class: "mt-2 bg-blue-500 hover:bg-blue-700 text-white rounded p-1 w-full" %>
        <% end %>
      </div>
      <div class="bg-gray-100 rounded">

      </div>

    </div >

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav class="h-16 bg-gray-50 ">
      <div class="flex justify-between items-center p-3">
        <p>Simple Airbnb</p>
        <%= link_to new_flat_path(@flat) do%>
        <div class="border border-blue-500 rounded hover:border-blue-700
        text-blue-500 hover:text-blue-700
        py-2 px-4">Add Flat</div>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>